name: Sandy Real CI
on:
  push:
    branches: main
  
jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: show files
      run: ls -l

    - name:  Build step
          run: echo "Building the project..."
echo     # Add your build commands here

    - name: Test step
      run: echo "Running tests..."
      # Add your test commands here