name: Sandy First CI
on:
  push:
    branches:
      - main
jobs:
  build
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      -name: Say Hello
       run: echo "Hello, World! CI/CD is awesome!"
       
